### ISSUE TITLE
Api Crash 

### ISSUE THREAD

**Issue by nisutec** [Murgeye/teamspeak3-python-api#10]
When a Teamspeak 5 Client leaves the server the `ClientLeftEvent` will Crash the Api with the following error.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "(hidden)\Anaconda3\envs\Teamspeak-Audit-Log-Bot\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "(hidden)\Anaconda3\envs\Teamspeak-Audit-Log-Bot\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "(hidden)\PycharmProjects\Teamspeak-Audit-Log-Bot\ts3API\TS3Connection.py", line 171, in _recv
    data = self._parse_resp(resp)
  File "(hidden)\PycharmProjects\Teamspeak-Audit-Log-Bot\ts3API\TS3Connection.py", line 439, in _parse_resp
    event = Events.EventParser.parse_event(event, event_type)
  File "(hidden)\PycharmProjects\Teamspeak-Audit-Log-Bot\ts3API\Events.py", line 66, in parse_event
    reason_id = int(event["reasonid"])
KeyError: 'reasonid'
```

**Comment by Murgeye** [comment]
This should be fixed. Sorry, I assumed that the ClientLeftEvent always had a reason id and didn't use get with a default value like I usually do when adding this line yesterday. Thanks for bringing this up. I think I will need to add some unit tests for the API soon.

**Comment by Murgeye** [comment]
Might I ask how you got access to the TeamSpeak 5 client? Up until this issue I was not even aware that there was a TeamSpeak 5 😅

**Comment by nisutec** [comment]
I have recieved a closed beta invitation to my Email Address for ca 5 weeks.

**Comment by nisutec** [comment]
You can try to catch a code on the Teamspeak Twitter Account to get access. There are sometimes posted which
