### ISSUE TITLE
Api Crash

### ISSUE THREAD

**Issue by nisutec** [Murgeye/teamspeak3-python-api#11]
After updating to Commit c910387bbe1f9417b6331c64b2812de23d6d11f2 i recieve the following error on starting

```
Traceback (most recent call last):
  File "(hidden)/PycharmProjects/Teamspeak-Audit-Log-Bot/main.py", line 1, in <module>
    from ts3API.TS3Connection import TS3Connection
  File "(hidden)\PycharmProjects\Teamspeak-Audit-Log-Bot\ts3API\TS3Connection.py", line 10, in <module>
    from ts3.Events import TS3Event
ModuleNotFoundError: No module named 'ts3'
```

**Comment by Murgeye** [comment]
Should be fixed, sorry my pycharm decided to add the directory name to some local imports.
